config/routes.rb
Wayne::Application.routes.draw do

  resources :problems

  root to: 'pages#home'

  match '/about', to: 'pages#about'
  match '/info', to: 'pages#info'
  match '/game', to: 'pages#game'
  match '/finish', to: 'pages#finish'

  get "game/new"
  get "game/problem"
  get "game/finish"
  post "game/answer"

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible :answer, :image, :quote, :value, :number, :guess_one, :guess_two
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/game_controller.rb
class GameController < ApplicationController

	def new
		session[:x] = 0
		session[:s] = 0
		session[:q] = 1
		session[:problems] = Problem.all.shuffle.collect(&:id)
		redirect_to "/game/problem"
	end

	def problem

		if session[:x] < 10
			@question = session[:q]
			@score = session[:s]
			session[:current] = session[:problems][session[:x]]
			session[:x] += 1
			session[:q] += 1
			@problem = Problem.find(session[:current])
		else 
			redirect_to "/game/finish"
		end

	end

	def answer
		if params[:answer] == Problem.find(session[:current]).answer
			session[:s] += 10
			redirect_to "/game/problem"
		else
			session[:s] -= 5
			redirect_to "/game/problem"
		end

	end


	def finish

		if (-100..0).include?(session[:s])
			@char = "Benjamin Oliver "
			@message = "You Suck!"
		elsif (1..10).include?(session[:s])
			@char = "Noah Vanderhoff"
			@message = "You Suck!"
		elsif (10..20).include?(session[:s])
			@char = "Russell"
			@message = "Boring."
		elsif (21..30).include?(session[:s])
			@char = "Stan Mikita"
			@message = "Creepy."
		elsif (31..40).include?(session[:s])
			@char = "Old Man Withers"
			@message = "Creepy."
		elsif (41..50).include?(session[:s])
			@char = "Officer Khoharksi"
			@message = "Cool!"
		elsif (51..60).include?(session[:s])
			@char = "Alice Cooper"
			@message = "Rock On!"
		elsif (61..70).include?(session[:s])
			@char = "Dream Girl"
			@message = "Awesome!"
		elsif (71..80).include?(session[:s])
			@char = "Cassandra"
			@message = "You Really Wail!"
		elsif (81..90).include?(session[:s])
			@char = "Garth"
			@message = "Party Time!"
		elsif (91..100).include?(session[:s])
			@char = "Wayne Campbell"
			@message = "Excellent!"
		else
		end

	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def info
  end

  def about
  end

  def game
  end

  def finish
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController

  before_filter :authenticate

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(params[:problem])

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render json: @problem, status: :created, location: @problem }
      else
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :no_content }
    end
  end

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "austinrory" && password == "gracieis1"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/game/_footer.html.erb
<footer>
	<a class="footer_link" href="/home/">Home</a>
	<a class="footer_link" href="/about">About</a>
	<a class="footer_link" href="#">All Games</a>
</footer>

app/views/game/answer.html.erb
<%= params[:answer] %>

app/views/game/finish.html.erb
<% provide :title, "Finish" %>

<body style="background-image:url(/images/char/<%=@char.downcase.split[0]%>.png)">

<div class="text" id="finish_text">
<p>You got <%= session[:s] %> points. <strong><%= @message %></strong> You earned the level of:</p>
<p style="font-size:45px"> <strong><%= @char %></strong></p>
</div>

<a class="button" id="home" href="/game/new" style="text-decoration:none">
		<div class="button_text">
			<p>Again!</p>
		</div>
</a>


</body>

app/views/game/problem.html.erb
<% provide :title, "Game" %>

<h1 class="title" id="question">Question #<%=@question%></h1>
<h1 class="title" id="question">Score = <span><%=@score%></span></h1>

<% @num=Problem.find_by_number(@problem.number) %>
<% @choices = [@num.answer, @num.guess_one, @num.guess_two].shuffle%>

<body style="background-image:url(<%=@num.image%>);background-size=100%">

 <div class="text" id="game">
    <%= @num.quote %>
    <%= form_tag "/game/answer", method: "post" do -%>
    	<div class="answers">
	      <label><input type="radio" name="answer" value = "<%=@choices[0]%>" onclick="this.form.submit()"> <%=@choices[0]%><br></label>
	      <label><input type="radio" name="answer" value = "<%=@choices[1]%>" onclick="this.form.submit()"> <%=@choices[1]%><br></label>
	      <label><input type="radio" name="answer" value = "<%=@choices[2]%>" onclick="this.form.submit()"> <%=@choices[2]%></label>
	    </div>
    <%- end -%>
  </div>

</body>

app/views/layouts/_footer.html.erb
<footer>
	<a class="footer_link" href="/">Home</a>
	<a class="footer_link" href="/about">About</a>
	<a class="footer_link" href="#">All Games</a>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wayne's World | <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
 
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41049315-1', 'waynesworldgame.com');
  ga('send', 'pageview');

	</script>

	<link href='http://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>

<%= render "/layouts/footer" %>
</html>

app/views/pages/_footer.html.erb
<footer>
	<a class="footer_link" href="/home/">Home</a>
	<a class="footer_link" href="/about">About</a>
	<a class="footer_link" href="#">All Games</a>
</footer>

app/views/pages/_problem.html.erb
<body style="background-image:url(<%=@rand.image%>);background-size=100%">

	<div class="q_text">
		<%= @rand.quote %>
	</div>

	<div class="question">
		<form id="form">
			<input type="text">
		</form>
	</div>

</body>

app/views/pages/about.html.erb
<% provide :title, "About" %>

<body style = "background-image:url(/images/batman.jpg); background-size:100%;">
	<h1 class="title">About</h1>
	<div class="text" id="about">
		<p>This is the first site ever built by me, Austin Rory Hackett. I hope you like it.</p>
	</div>
</body>

app/views/pages/finish.html.erb
<% provide :title, "Finish" %>

<!-- case | when $s / @char / @message -->

<% @message = "Excellent!!!"; @char = "Wayne Campbell"; %>

<%= render "finish/char" %>

app/views/pages/game.html.erb
<% provide :title, "Game" %>

<% game.new %>

<% game.show %>

app/views/pages/home.html.erb
<% provide :title, "Home" %>

<body id="home_back">
	<h1 class="title">Welcome to the Wayne's World Game!</h1>
	<a class="button" id="home" href="/info" style="text-decoration:none">
		<div class="button_text">
			<p>Party On!</p>
		</div>
	</a>
</body>

app/views/pages/info.html.erb
<% provide :title, "Info" ;%>

<body id="info_back">
	<h1 class="title">Instructions</h1>
	<div class="text">
		<p>You will be presented with unfinished quotes from the (greatest) movie (of all time).</p>
		<br>
		<p>You need to finish the sentence correctly in order to gain points. At the end,</p>
		<p>your points will be tallied and we we'll see how big of a fan you really are.</p>
		<br>
		<p>Ready? Click the button below to begin.<p>
	</div>
	<div class="info">
	</div>
	<a class="button" id="info" href="/game/new" style="text-decoration:none">
		<div class="button_text">
			<p>Party On!</p>
		</div>
	</a>
</body>

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_field :quote %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :guess_one %><br />
    <%= f.text_field :guess_one %>
  </div>
  <div class="field">
    <%= f.label :guess_two %><br />
    <%= f.text_field :guess_two %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<h1>Listing problems</h1>

<table>
  <tr>
    <th>Quote</th>
    <th>Answer</th>
    <th>Guess One</th>
    <th>Guess Two</th>
    <th>Image</th>
    <th>Number</th>
    <th></th>
    <th></th>
  </tr>

<% @problems.each do |problem| %>
  <tr>
    <td><%= problem.quote %></td>
    <td><%= problem.answer %></td>
    <td><%= problem.guess_two %></td>
    <td><%= problem.guess_one %></td>
    <td><%= problem.image %></td>
    <td><%= problem.number %></td>
    <td><%= link_to 'Show', problem %></td>
    <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
    <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/new.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<% provide :title, "Display" %>

<h1 class="title">Problem #<%=@problem.number%></h1>

<body style="background-image:url(<%=@problem.image%>);background-size=100%">

  <div class="text" id="display">
    <%= @problem.quote %>
    <form>
      <div class="answers">
<input type="radio" name="answer" value = "<%=@problem.answer%>" onclick="this.form.submit()"> <%=@problem.answer%><br>
<input type="radio" name="answer" value = "<%=@problem.guess_one%>" onclick="this.form.submit()"> <%=@problem.guess_one%><br>
<input type="radio" name="answer" value = "<%=@problem.guess_two%>" onclick="this.form.submit()"> <%=@problem.guess_two%>
	    </div>
    </form>
  </div>

</body>